### ISSUE TITLE
Update extension to match new Stryd PowerCenter UI

### ISSUE THREAD

**Issue by tovin07** [divad1978/REChromeExtension#1]
Hi @divad1978,

This is a really great Chrome Extension. Thank you for doing the work.
Stryd PowerCenter has updated the UI, and it breaks the ability of this extension to display RE (and other metrics) in lap table.
By the way, I see that the code in this github repo does not match the code of version 1.3 (latest release on Chrome WebStore).
Can you update the code, and release a new version of this extension to fix those problems?

Thank you.

**Comment by divad1978** [comment]
Hello Tovin,

I probably won't have a new update until the weekend. I have it mostly done
just finding time to fix some minor details and then package it up. When I
release it I'll update github.

Thanks,

David Juiliano

**Comment by tovin07** [comment]
Hello David,

Thank you very much.
